/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projectuas.pbo;

import javafx.application.Application;
import javafx.stage.Stage;

public class App extends Application {

    public static void main(String[] args) {
        launch();
    }

    @Override
    public void start(Stage stage) {
        Scenes scene=new Scenes(stage);
        scene.mainMenu();
    }
}
